### PR TITLE
Add PHP 8.2 Support

### PR DESCRIPTION
**Pull request by patinthehat**
This PR adds PHP 8.2 to the tests workflow.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by riasvdv** [comment]
Why is the Carbon dependency necessary? We don't use it directly in this package

**Comment by patinthehat** [comment]
@riasvdv I'm working on fine-tuning an automation script i wrote for updating packages, and it was added because laravel requires it and `laravel-onboard` is the package name (so the script made an assumption).  

I'll submit another PR to remove it. Sorry about that!

**Comment by riasvdv** [comment]
No problem! Thanks for the PR(s)

**Pull request merged**
